AWSTemplateFormatVersion: "2010-09-09"
Description: Create GitHub Actions OIDC Provider 

Parameters:

  GitHubCertificate:
    Type: String

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - !Ref GitHubCertificate



